Add redux
StanisLove/blog-platform-on-react pull request #6
Opened 2017-02-25 06:10 UTC by StanisLove

2017-02-28 07:10 UTC, index01d requested changes

2017-02-28 07:10 UTC, index01d commented on src/actions/posts/postLiked.js
> +  const entries = store.getState().posts.entries.map(function(obj) {
должно быть сделано в reducer'е, action должен только возвращать описание действия

2017-02-28 07:12 UTC, index01d requested changes

2017-02-28 07:12 UTC, index01d commented on src/actions/posts/postLiked.js
> +  const entries = store.getState().posts.entries.map(function(obj) {
нельзя так просто взять и подключить store в любом месте, где захочется:)

2017-02-28 08:49 UTC, StanisLove commented on src/actions/posts/postLiked.js
> +  const entries = store.getState().posts.entries.map(function(obj) {
Если я сделаю это в reducer'е, он будет по-прежнему чистой функцией? Я же могу изменить store в другом месте, и тогда при одних и тех же входных параметрах на выходе будет разный результат?

2017-02-28 08:51 UTC, index01d commented on src/actions/posts/postLiked.js
> +  const entries = store.getState().posts.entries.map(function(obj) {
ты не можешь изменить состояние в store в другом месте.

2017-02-28 08:51 UTC, index01d commented on src/actions/posts/postLiked.js
> +  const entries = store.getState().posts.entries.map(function(obj) {
минуя dispatch

2017-02-28 08:52 UTC, index01d commented on src/actions/posts/postLiked.js
> +  const entries = store.getState().posts.entries.map(function(obj) {
reducer при этом останется чистой функцией потому как расчитывает результат на основе состояния, которое приходит в параметре

2017-03-04 21:54 UTC, index01d approved these changes

2017-03-08 17:39 UTC, merged